import json
from pathlib import Path

sample_path = Path("notebooks/sample_run_single_game.ipynb")
sub_path = Path("notebooks/submission_run.ipynb")

cell_1_code = [
    "import json\n",
    "import os\n",
    "from pathlib import Path\n",
    "import subprocess\n",
    "import sys\n",
    "import sysconfig\n",
    "import time\n",
    "import accelerate\n",
    "import torch\n",
    "import transformers\n",
    "\n",
    "print(f\"Transformers : {transformers.__version__}\")\n",
    "print(f\"Accelerate   : {accelerate.__version__}\")\n",
    "print(f\"PyTorch      : {torch.__version__}\")\n",
    "print(f\"CUDA Version : {torch.version.cuda}\")\n",
    "\n",
    "# 1. Hotfix for Kaggle Python 3.12 Pillow / torchvision typing mismatch\n",
    "try:\n",
    "    import PIL._typing\n",
    "    if not hasattr(PIL._typing, \"_Ink\"):\n",
    "        from typing import Union, Tuple, Sequence\n",
    "        PIL._typing._Ink = Union[Tuple[int, ...], str, int, float, Sequence[int]]\n",
    "except Exception:\n",
    "    pass\n",
    "\n",
    "# 2. Register 'gemma4' architecture cleanly without model_type mismatch\n",
    "try:\n",
    "    from transformers import AutoConfig, GemmaConfig\n",
    "    gemma_base_cfg = getattr(transformers, \"Gemma2Config\", GemmaConfig)\n",
    "    gemma4_cfg_cls = getattr(transformers, \"Gemma4Config\", None)\n",
    "\n",
    "    if gemma4_cfg_cls is None:\n",
    "        class Gemma4Config(gemma_base_cfg):\n",
    "            model_type = \"gemma4\"\n",
    "        AutoConfig.register(\"gemma4\", Gemma4Config)\n",
    "        gemma4_cfg_cls = Gemma4Config\n",
    "        print(\"✅ Cleanly registered subclassed 'Gemma4Config' in AutoConfig!\")\n",
    "    else:\n",
    "        print(\"✅ Native Gemma4Config detected in Transformers.\")\n",
    "except Exception as e:\n",
    "    print(f\"ℹ️ AutoConfig registration note: {e}\")\n",
    "\n",
    "# 3. GLOBAL HOTFIX: Prevent pad_token_id list crash (< not supported between list and int)\n",
    "from transformers.generation.configuration_utils import GenerationConfig\n",
    "\n",
    "# Pre-empt factory.py's patch so it won't assign a list to pad_token_id\n",
    "if gemma4_cfg_cls is not None:\n",
    "    gemma4_cfg_cls._patched_pad_token = True\n",
    "    _orig_g4_init = gemma4_cfg_cls.__init__\n",
    "    def _safe_g4_init(self, *args, **kwargs):\n",
    "        _orig_g4_init(self, *args, **kwargs)\n",
    "        if hasattr(self, \"pad_token_id\") and isinstance(self.pad_token_id, (list, tuple)):\n",
    "            self.pad_token_id = self.pad_token_id[0] if self.pad_token_id else 0\n",
    "        elif not hasattr(self, \"pad_token_id\") or self.pad_token_id is None:\n",
    "            eos = getattr(self, \"eos_token_id\", 1)\n",
    "            self.pad_token_id = eos[0] if isinstance(eos, (list, tuple)) else (eos or 0)\n",
    "    gemma4_cfg_cls.__init__ = _safe_g4_init\n",
    "\n",
    "# Monkey-patch GenerationConfig.validate to guarantee pad_token_id is an int\n",
    "_orig_validate = GenerationConfig.validate\n",
    "def _safe_validate(self, *args, **kwargs):\n",
    "    if isinstance(getattr(self, \"pad_token_id\", None), (list, tuple)):\n",
    "        self.pad_token_id = self.pad_token_id[0] if len(self.pad_token_id) > 0 else 0\n",
    "    if isinstance(getattr(self, \"bos_token_id\", None), (list, tuple)):\n",
    "        self.bos_token_id = self.bos_token_id[0] if len(self.bos_token_id) > 0 else 2\n",
    "    return _orig_validate(self, *args, **kwargs)\n",
    "GenerationConfig.validate = _safe_validate\n",
    "\n",
    "# Monkey-patch GenerationConfig.__init__\n",
    "_orig_gen_init = GenerationConfig.__init__\n",
    "def _safe_gen_init(self, *args, **kwargs):\n",
    "    for k in [\"pad_token_id\", \"bos_token_id\"]:\n",
    "        if k in kwargs and isinstance(kwargs[k], (list, tuple)):\n",
    "            kwargs[k] = kwargs[k][0] if len(kwargs[k]) > 0 else 0\n",
    "    _orig_gen_init(self, *args, **kwargs)\n",
    "    if isinstance(getattr(self, \"pad_token_id\", None), (list, tuple)):\n",
    "        self.pad_token_id = self.pad_token_id[0] if len(self.pad_token_id) > 0 else 0\n",
    "GenerationConfig.__init__ = _safe_gen_init\n",
    "\n",
    "# Monkey-patch GenerationConfig.from_model_config\n",
    "_orig_from_model_config = GenerationConfig.from_model_config\n",
    "@classmethod\n",
    "def _safe_from_model_config(cls, model_config):\n",
    "    if hasattr(model_config, \"pad_token_id\") and isinstance(model_config.pad_token_id, (list, tuple)):\n",
    "        model_config.pad_token_id = model_config.pad_token_id[0] if len(model_config.pad_token_id) > 0 else 0\n",
    "    if hasattr(model_config, \"text_config\"):\n",
    "        t_cfg = getattr(model_config, \"text_config\")\n",
    "        if hasattr(t_cfg, \"pad_token_id\") and isinstance(getattr(t_cfg, \"pad_token_id\"), (list, tuple)):\n",
    "            t_cfg.pad_token_id = t_cfg.pad_token_id[0] if len(t_cfg.pad_token_id) > 0 else 0\n",
    "    try:\n",
    "        gen_cfg = _orig_from_model_config(model_config)\n",
    "    except Exception:\n",
    "        gen_cfg = cls()\n",
    "    if isinstance(getattr(gen_cfg, \"pad_token_id\", None), (list, tuple)):\n",
    "        gen_cfg.pad_token_id = gen_cfg.pad_token_id[0] if len(gen_cfg.pad_token_id) > 0 else 0\n",
    "    return gen_cfg\n",
    "GenerationConfig.from_model_config = _safe_from_model_config\n",
    "\n",
    "print(\"✅ Applied global runtime hotfixes for Gemma4 and GenerationConfig!\")\n",
    "\n",
    "# Set runtime environment flags\n",
    "os.environ[\"MPLBACKEND\"] = \"Agg\"\n",
    "os.environ[\"ONLY_RESET_LEVELS\"] = \"true\"\n",
    "os.environ[\"TOKENIZERS_PARALLELISM\"] = \"false\"\n",
    "os.environ[\"TRANSFORMERS_VERBOSITY\"] = \"error\"\n",
    "\n",
    "# Prepend CUDA library path for PyTorch / GPU runtime\n",
    "cuda_lib = \"/usr/local/nvidia/lib64\"\n",
    "if Path(cuda_lib).exists():\n",
    "    os.environ[\"LIBRARY_PATH\"] = os.pathsep.join(\n",
    "        e for e in [cuda_lib, *os.environ.get(\"LIBRARY_PATH\", \"\").split(os.pathsep)] if e\n",
    "    )\n",
    "\n",
    "# Working directory\n",
    "WORKING_DIR = Path(\"/kaggle/working\")\n",
    "WORKING_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# Hardware Detection\n",
    "if torch.cuda.is_available():\n",
    "    gpu_name = torch.cuda.get_device_name(0)\n",
    "    vram_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)\n",
    "    print(f\"Detected GPU: {gpu_name} ({vram_gb:.2f} GB VRAM)\")\n"
]

cell_3_code_sample = [
    "# Load configuration\n",
    "config_candidates = [\n",
    "    source_dir.parent / \"configs\" / \"default.yaml\",\n",
    "    Path(\"configs/default.yaml\"),\n",
    "]\n",
    "cfg_path = next((p for p in config_candidates if p.exists()), None)\n",
    "config = AppConfig.from_yaml(cfg_path) if cfg_path else AppConfig()\n",
    "\n",
    "# Point directly to local offline weights\n",
    "local_model_path = Path(\"/kaggle/input/datasets/spiritofvishwakarma/gemma4-26b-a4b-q4-with-mmprojq8-gguf/Gemma-4-26B-A4B-NVFP4\")\n",
    "if local_model_path.exists():\n",
    "    config.model.model_id = str(local_model_path)\n",
    "    print(f\"📦 Using Local Model Path: {config.model.model_id}\")\n",
    "else:\n",
    "    for cand in Path(\"/kaggle/input\").rglob(\"Gemma-4*\"):\n",
    "        if cand.is_dir():\n",
    "            config.model.model_id = str(cand)\n",
    "            print(f\"🔍 Located model directory at: {config.model.model_id}\")\n",
    "            break\n",
    "\n",
    "config.model.device = \"cuda:0\" if torch.cuda.is_available() else \"cpu\"\n",
    "config.model.torch_dtype = \"bfloat16\" if torch.cuda.is_bf16_supported() else \"float16\"\n",
    "config.model.attn_implementation = \"sdpa\"\n",
    "config.agent.memory_root = \"/kaggle/working/agent_memory\"\n",
    "config.agent.vision_cache_dir = \"/tmp/agent_vision\"\n",
    "\n",
    "USE_MOCK = not torch.cuda.is_available()\n",
    "\n",
    "print(f\"🚀 Instantiating LangChain ChatModel (Mock: {USE_MOCK})...\")\n",
    "llm = ModelFactory.create_model(config.model, use_mock=USE_MOCK)\n",
    "\n",
    "# Build Perceptual, Debugger, Planning, and Review Chains\n",
    "eye_chain = EyeChain(llm, max_tokens=config.model.max_new_tokens_eye)\n",
    "debugger_chain = DebuggerChain(llm, max_tokens=config.model.max_new_tokens_debug)\n",
    "brain_chain = BrainChain(llm, max_tokens=config.model.max_new_tokens_brain)\n",
    "reviewer_chain = ReviewerChain(llm, max_tokens=config.model.max_new_tokens_review)\n",
    "\n",
    "try:\n",
    "    from arcengine import GameState\n",
    "    resolver = GameStateResolver(GameState)\n",
    "except ImportError:\n",
    "    resolver = GameStateResolver(None)\n",
    "\n",
    "agent = ARCLangChainAgent(\n",
    "    eye_chain=eye_chain,\n",
    "    debugger_chain=debugger_chain,\n",
    "    brain_chain=brain_chain,\n",
    "    reviewer_chain=reviewer_chain,\n",
    "    resolver=resolver,\n",
    "    stuck_threshold=config.agent.stuck_threshold,\n",
    "    memory_root=config.agent.memory_root,\n",
    "    vision_cache_dir=config.agent.vision_cache_dir,\n",
    ")\n",
    "runner = ARCRunner(agent=agent, time_budget_hours=config.agent.time_budget_hours)\n",
    "print(\"✅ LangChain ARC-AGI-3 Agent ready!\")"
]

cell_3_code_sub = [
    "# Load configuration\n",
    "config_candidates = [\n",
    "    source_dir.parent / \"configs\" / \"kaggle_offline.yaml\",\n",
    "    Path(\"configs/kaggle_offline.yaml\"),\n",
    "]\n",
    "cfg_path = next((p for p in config_candidates if p.exists()), None)\n",
    "config = AppConfig.from_yaml(cfg_path) if cfg_path else AppConfig()\n",
    "\n",
    "# Point directly to local offline weights\n",
    "local_model_path = Path(\"/kaggle/input/datasets/spiritofvishwakarma/gemma4-26b-a4b-q4-with-mmprojq8-gguf/Gemma-4-26B-A4B-NVFP4\")\n",
    "if local_model_path.exists():\n",
    "    config.model.model_id = str(local_model_path)\n",
    "    print(f\"📦 Using Local Model Path: {config.model.model_id}\")\n",
    "else:\n",
    "    for cand in Path(\"/kaggle/input\").rglob(\"Gemma-4*\"):\n",
    "        if cand.is_dir():\n",
    "            config.model.model_id = str(cand)\n",
    "            print(f\"🔍 Located model directory at: {config.model.model_id}\")\n",
    "            break\n",
    "\n",
    "config.model.device = \"cuda:0\" if torch.cuda.is_available() else \"cpu\"\n",
    "config.model.torch_dtype = \"bfloat16\" if torch.cuda.is_bf16_supported() else \"float16\"\n",
    "config.model.attn_implementation = \"sdpa\"\n",
    "config.agent.memory_root = \"/kaggle/working/agent_memory\"\n",
    "config.agent.vision_cache_dir = \"/tmp/agent_vision\"\n",
    "config.environment.submission_parquet = \"/kaggle/working/submission.parquet\"\n",
    "\n",
    "print(f\"🚀 Loading {config.model.model_id} on {config.model.device} ({config.model.torch_dtype})...\")\n",
    "llm = ModelFactory.create_model(config.model, use_mock=False)\n",
    "\n",
    "# Build LangChain cognitive chains\n",
    "eye_chain = EyeChain(llm, max_tokens=config.model.max_new_tokens_eye)\n",
    "debugger_chain = DebuggerChain(llm, max_tokens=config.model.max_new_tokens_debug)\n",
    "brain_chain = BrainChain(llm, max_tokens=config.model.max_new_tokens_brain)\n",
    "reviewer_chain = ReviewerChain(llm, max_tokens=config.model.max_new_tokens_review)\n",
    "\n",
    "try:\n",
    "    from arcengine import GameState\n",
    "    resolver = GameStateResolver(GameState)\n",
    "except ImportError:\n",
    "    resolver = GameStateResolver(None)\n",
    "\n",
    "agent = ARCLangChainAgent(\n",
    "    eye_chain=eye_chain,\n",
    "    debugger_chain=debugger_chain,\n",
    "    brain_chain=brain_chain,\n",
    "    reviewer_chain=reviewer_chain,\n",
    "    resolver=resolver,\n",
    "    stuck_threshold=config.agent.stuck_threshold,\n",
    "    memory_root=config.agent.memory_root,\n",
    "    vision_cache_dir=config.agent.vision_cache_dir,\n",
    ")\n",
    "runner = ARCRunner(agent=agent, time_budget_hours=config.agent.time_budget_hours)\n",
    "print(\"✅ Unified LangChain Agent initialized on RTX PRO 6000!\")"
]

def update_nb(nb_path, c3_code):
    with open(nb_path, "r", encoding="utf-8") as f:
        nb = json.load(f)

    # Find Cell 1 (under header "1. Environment Detection...")
    for idx, cell in enumerate(nb["cells"]):
        if cell.get("cell_type") == "markdown" and "1. Environment Detection" in "".join(cell.get("source", [])):
            if idx + 1 < len(nb["cells"]) and nb["cells"][idx+1].get("cell_type") == "code":
                nb["cells"][idx+1]["source"] = cell_1_code
                print(f"Updated Cell 1 in {nb_path.name}")
                break

    # Find Cell 3 (under header "3. Initialize...")
    for idx, cell in enumerate(nb["cells"]):
        if cell.get("cell_type") == "markdown" and "3. Initialize" in "".join(cell.get("source", [])):
            if idx + 1 < len(nb["cells"]) and nb["cells"][idx+1].get("cell_type") == "code":
                nb["cells"][idx+1]["source"] = c3_code
                print(f"Updated Cell 3 in {nb_path.name}")
                break

    with open(nb_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1)

update_nb(sample_path, cell_3_code_sample)
update_nb(sub_path, cell_3_code_sub)
