import json
from pathlib import Path

sample_path = Path("notebooks/sample_run_single_game.ipynb")
sub_path = Path("notebooks/submission_run.ipynb")

cell1_source = [
    "import json\n",
    "import os\n",
    "from pathlib import Path\n",
    "import subprocess\n",
    "import sys\n",
    "import sysconfig\n",
    "import time\n",
    "import accelerate\n",
    "import torch\n",
    "import transformers\n",
    "\n",
    "print(f\"Transformers : {transformers.__version__}\")\n",
    "print(f\"Accelerate   : {accelerate.__version__}\")\n",
    "print(f\"PyTorch      : {torch.__version__}\")\n",
    "print(f\"CUDA Version : {torch.version.cuda}\")\n",
    "\n",
    "# 1. Hotfix for Kaggle Python 3.12 Pillow / torchvision typing mismatch\n",
    "try:\n",
    "    import PIL._typing\n",
    "    if not hasattr(PIL._typing, \"_Ink\"):\n",
    "        from typing import Union, Tuple, Sequence\n",
    "        PIL._typing._Ink = Union[Tuple[int, ...], str, int, float, Sequence[int]]\n",
    "except Exception:\n",
    "    pass\n",
    "\n",
    "# 2. Register 'gemma4' architecture cleanly without model_type mismatch\n",
    "try:\n",
    "    from transformers import AutoConfig, GemmaConfig\n",
    "    gemma_base_cfg = getattr(transformers, \"Gemma2Config\", GemmaConfig)\n",
    "    gemma4_cfg_cls = getattr(transformers, \"Gemma4Config\", None)\n",
    "\n",
    "    if gemma4_cfg_cls is None:\n",
    "        class Gemma4Config(gemma_base_cfg):\n",
    "            model_type = \"gemma4\"\n",
    "        AutoConfig.register(\"gemma4\", Gemma4Config)\n",
    "        gemma4_cfg_cls = Gemma4Config\n",
    "        print(\"✅ Cleanly registered subclassed 'Gemma4Config' in AutoConfig!\")\n",
    "    else:\n",
    "        print(\"✅ Native Gemma4Config detected in Transformers.\")\n",
    "\n",
    "    # Allow global per-layer attribute access for heterogeneous Gemma4 MoE layers\n",
    "    setattr(gemma4_cfg_cls, 'allow_global_per_layer_attribute_access', True)\n",
    "    if hasattr(transformers, 'PretrainedConfig'):\n",
    "        transformers.PretrainedConfig.allow_global_per_layer_attribute_access = True\n",
    "\n",
    "    # Proxy vocab_size and text_config attrs so Gemma2/internal checks don't crash\n",
    "    # (NOTE: Do NOT include 'head_dim' here, as heterogeneous layers handle head_dim per-layer!)\n",
    "    _TEXT_CFG_PROXIED = [\n",
    "        'vocab_size', 'hidden_size', 'num_hidden_layers', 'num_attention_heads',\n",
    "        'num_key_value_heads', 'intermediate_size', 'rms_norm_eps',\n",
    "    ]\n",
    "    if gemma4_cfg_cls is not None and not hasattr(gemma4_cfg_cls, '_patched_vocab_proxy'):\n",
    "        def _make_proxy(attr):\n",
    "            def _proxy(self):\n",
    "                text_cfg = getattr(self, 'text_config', None)\n",
    "                if text_cfg is not None and text_cfg is not self and not isinstance(text_cfg, dict):\n",
    "                    if hasattr(text_cfg, '__dict__') and attr in text_cfg.__dict__:\n",
    "                        return text_cfg.__dict__[attr]\n",
    "                    if not isinstance(text_cfg, gemma4_cfg_cls):\n",
    "                        return getattr(text_cfg, attr, None)\n",
    "                elif isinstance(text_cfg, dict):\n",
    "                    return text_cfg.get(attr)\n",
    "                return None\n",
    "            _proxy.__name__ = attr\n",
    "            return property(_proxy)\n",
    "        for _attr in _TEXT_CFG_PROXIED:\n",
    "            if not hasattr(gemma4_cfg_cls, _attr):\n",
    "                setattr(gemma4_cfg_cls, _attr, _make_proxy(_attr))\n",
    "        gemma4_cfg_cls._patched_vocab_proxy = True\n",
    "        print(\"🔧 Patched Gemma4Config with text_config attribute proxies.\")\n",
    "\n",
    "    # Safely wrap __init__ once to sanitize pad_token_id/eos_token_id without recursion\n",
    "    if gemma4_cfg_cls is not None and not hasattr(gemma4_cfg_cls, '_patched_pad_done'):\n",
    "        _curr_init = gemma4_cfg_cls.__init__\n",
    "        _orig_init = getattr(gemma4_cfg_cls, '_orig_raw_init', _curr_init)\n",
    "        gemma4_cfg_cls._orig_raw_init = _orig_init\n",
    "        def _safe_init(self, *args, _init_fn=_orig_init, **kwargs):\n",
    "            setattr(self, 'allow_global_per_layer_attribute_access', True)\n",
    "            _init_fn(self, *args, **kwargs)\n",
    "            setattr(self, 'allow_global_per_layer_attribute_access', True)\n",
    "            for _tok in ('pad_token_id', 'eos_token_id', 'bos_token_id'):\n",
    "                val = getattr(self, _tok, None)\n",
    "                if isinstance(val, (list, tuple)):\n",
    "                    setattr(self, _tok, val[0] if val else 0)\n",
    "            if not hasattr(self, 'pad_token_id') or self.pad_token_id is None:\n",
    "                eos = getattr(self, 'eos_token_id', 1)\n",
    "                self.pad_token_id = eos[0] if isinstance(eos, (list, tuple)) else (eos or 0)\n",
    "            if not hasattr(self, 'eos_token_id') or self.eos_token_id is None:\n",
    "                self.eos_token_id = 1\n",
    "            if isinstance(self.pad_token_id, (list, tuple)):\n",
    "                self.pad_token_id = self.pad_token_id[0] if self.pad_token_id else 0\n",
    "        gemma4_cfg_cls.__init__ = _safe_init\n",
    "        gemma4_cfg_cls._patched_pad_done = True\n",
    "        gemma4_cfg_cls._patched_pad_token = True\n",
    "        gemma4_cfg_cls._patched_pad_int = True\n",
    "        print(\"🔧 Safely patched Gemma4Config __init__ (recursion-free).\")\n",
    "except Exception as e:\n",
    "    print(f\"ℹ️ AutoConfig registration note: {e}\")\n",
    "\n",
    "# 3. GLOBAL HOTFIX: Prevent pad_token_id list crash (< not supported between list and int)\n",
    "from transformers.generation.configuration_utils import GenerationConfig\n",
    "\n",
    "if not hasattr(GenerationConfig, '_orig_raw_validate'):\n",
    "    GenerationConfig._orig_raw_validate = getattr(GenerationConfig, 'validate', lambda s, *a, **k: None)\n",
    "if not hasattr(GenerationConfig, '_orig_raw_init'):\n",
    "    GenerationConfig._orig_raw_init = GenerationConfig.__init__\n",
    "if not hasattr(GenerationConfig, '_orig_raw_fmc'):\n",
    "    GenerationConfig._orig_raw_fmc = GenerationConfig.from_model_config\n",
    "if not hasattr(GenerationConfig, '_orig_raw_fd'):\n",
    "    GenerationConfig._orig_raw_fd = GenerationConfig.from_dict\n",
    "\n",
    "_orig_validate = GenerationConfig._orig_raw_validate\n",
    "_orig_gen_init = GenerationConfig._orig_raw_init\n",
    "_orig_from_model_config = GenerationConfig._orig_raw_fmc\n",
    "_orig_from_dict = GenerationConfig._orig_raw_fd\n",
    "\n",
    "if not hasattr(GenerationConfig, '_patched_validate_done'):\n",
    "    def _safe_validate(self, *args, _val_fn=_orig_validate, **kwargs):\n",
    "        if isinstance(getattr(self, \"pad_token_id\", None), (list, tuple)):\n",
    "            self.pad_token_id = self.pad_token_id[0] if len(self.pad_token_id) > 0 else 0\n",
    "        if isinstance(getattr(self, \"bos_token_id\", None), (list, tuple)):\n",
    "            self.bos_token_id = self.bos_token_id[0] if len(self.bos_token_id) > 0 else 2\n",
    "        return _val_fn(self, *args, **kwargs)\n",
    "    GenerationConfig.validate = _safe_validate\n",
    "    GenerationConfig._patched_validate_done = True\n",
    "\n",
    "if not hasattr(GenerationConfig, '_patched_init_done'):\n",
    "    def _safe_gen_init(self, *args, _init_fn=_orig_gen_init, **kwargs):\n",
    "        for k in [\"pad_token_id\", \"bos_token_id\"]:\n",
    "            if k in kwargs and isinstance(kwargs[k], (list, tuple)):\n",
    "                kwargs[k] = kwargs[k][0] if len(kwargs[k]) > 0 else 0\n",
    "        _init_fn(self, *args, **kwargs)\n",
    "        if isinstance(getattr(self, \"pad_token_id\", None), (list, tuple)):\n",
    "            self.pad_token_id = self.pad_token_id[0] if len(self.pad_token_id) > 0 else 0\n",
    "    GenerationConfig.__init__ = _safe_gen_init\n",
    "    GenerationConfig._patched_init_done = True\n",
    "\n",
    "if not hasattr(GenerationConfig, '_patched_fmc_done'):\n",
    "    @classmethod\n",
    "    def _safe_from_model_config(cls, model_config, _fmc_fn=_orig_from_model_config):\n",
    "        if hasattr(model_config, \"pad_token_id\") and isinstance(model_config.pad_token_id, (list, tuple)):\n",
    "            model_config.pad_token_id = model_config.pad_token_id[0] if len(model_config.pad_token_id) > 0 else 0\n",
    "        if hasattr(model_config, \"text_config\"):\n",
    "            t_cfg = getattr(model_config, \"text_config\")\n",
    "            if hasattr(t_cfg, \"pad_token_id\") and isinstance(getattr(t_cfg, \"pad_token_id\"), (list, tuple)):\n",
    "                t_cfg.pad_token_id = t_cfg.pad_token_id[0] if len(t_cfg.pad_token_id) > 0 else 0\n",
    "        try:\n",
    "            gen_cfg = _fmc_fn(model_config)\n",
    "        except Exception:\n",
    "            gen_cfg = cls()\n",
    "        if isinstance(getattr(gen_cfg, \"pad_token_id\", None), (list, tuple)):\n",
    "            gen_cfg.pad_token_id = gen_cfg.pad_token_id[0] if len(gen_cfg.pad_token_id) > 0 else 0\n",
    "        return gen_cfg\n",
    "    GenerationConfig.from_model_config = _safe_from_model_config\n",
    "    GenerationConfig._patched_fmc_done = True\n",
    "\n",
    "# Hotfix for safetensors.safe_open unexpected keyword argument 'backend'\n",
    "try:\n",
    "    import safetensors\n",
    "    if not hasattr(safetensors, '_raw_unpatched_safe_open'):\n",
    "        safetensors._raw_unpatched_safe_open = safetensors.safe_open\n",
    "    _raw_safe_open = safetensors._raw_unpatched_safe_open\n",
    "    def _compat_safe_open(*args, _target_fn=_raw_safe_open, **kwargs):\n",
    "        try:\n",
    "            return _target_fn(*args, **kwargs)\n",
    "        except TypeError as te:\n",
    "            if \"backend\" in str(te):\n",
    "                kwargs.pop(\"backend\", None)\n",
    "                return _target_fn(*args, **kwargs)\n",
    "            raise te\n",
    "    safetensors.safe_open = _compat_safe_open\n",
    "    if hasattr(safetensors, \"torch\"):\n",
    "        safetensors.torch.safe_open = _compat_safe_open\n",
    "    import sys\n",
    "    for mod in list(sys.modules.values()):\n",
    "        if mod and hasattr(mod, \"safe_open\") and getattr(mod, \"safe_open\") is not _compat_safe_open:\n",
    "            try:\n",
    "                setattr(mod, \"safe_open\", _compat_safe_open)\n",
    "            except Exception:\n",
    "                pass\n",
    "    safetensors._patched_safe_open = True\n",
    "    print(\"✅ Applied safetensors safe_open compatibility patch!\")\n",
    "except Exception as e:\n",
    "    pass\n",
    "print(\"✅ Applied global runtime hotfixes for Gemma4 and GenerationConfig!\")\n",
    "\n",
    "# Set runtime environment flags\n",
    "os.environ[\"MPLBACKEND\"] = \"Agg\"\n",
    "os.environ[\"ONLY_RESET_LEVELS\"] = \"true\"\n",
    "os.environ[\"TOKENIZERS_PARALLELISM\"] = \"false\"\n",
    "os.environ[\"TRANSFORMERS_VERBOSITY\"] = \"error\"\n",
    "\n",
    "# Prepend CUDA library path for PyTorch / GPU runtime\n",
    "cuda_lib = \"/usr/local/nvidia/lib64\"\n",
    "if Path(cuda_lib).exists():\n",
    "    os.environ[\"LIBRARY_PATH\"] = os.pathsep.join(\n",
    "        e for e in [cuda_lib, *os.environ.get(\"LIBRARY_PATH\", \"\").split(os.pathsep)] if e\n",
    "    )\n",
    "\n",
    "# Working directory\n",
    "WORKING_DIR = Path(\"/kaggle/working\")\n",
    "WORKING_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# Hardware Detection\n",
    "if torch.cuda.is_available():\n",
    "    gpu_name = torch.cuda.get_device_name(0)\n",
    "    vram_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)\n",
    "    print(f\"Detected GPU: {gpu_name} ({vram_gb:.2f} GB VRAM)\")\n",
]

# Process both notebooks
for p in [sample_path, sub_path]:
    with open(p, "r", encoding="utf-8") as f:
        nb = json.load(f)

    for cell in nb["cells"]:
        if cell.get("cell_type") == "code":
            src = "".join(cell.get("source", []))
            # 1. Update Cell 1
            if "Accelerate   :" in src and "Gemma4Config" in src:
                cell["source"] = cell1_source
                print(f"Updated Cell 1 in {p.name}")
            
            # 2. Clean Cell 3 (remove duplicate safetensors patch)
            if "ModelFactory.create_model" in src and "safetensors" in src:
                lines = cell.get("source", [])
                new_lines = []
                skipping = False
                for line in lines:
                    if "# Hotfix for safetensors.safe_open" in line or "try:\n" in line and "import safetensors" in "".join(lines):
                        pass
                    # Filter out duplicate safetensors block
                    if "# Hotfix for safetensors.safe_open" in line:
                        skipping = True
                        continue
                    if skipping:
                        if "llm = ModelFactory.create_model" in line:
                            skipping = False
                            new_lines.append(line)
                        continue
                    new_lines.append(line)
                cell["source"] = new_lines
                print(f"Cleaned duplicate safetensors patch from Cell 3 in {p.name}")

    with open(p, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1)

print("Finished notebook updates.")
